# Generated by Django 3.2.10 on 2024-05-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
