# Generated by Django 3.2.10 on 2024-05-13 16:43

from django.db import migrations, models

def populate_full_name(apps, schema_editor):
    Student = apps.get_model('quickstart', 'Student')  # Replace 'quickstart' with the name of your app
    for student in Student.objects.all():
        student.full_name = f"{student.first_name} {student.last_name}"
        student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_remove_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, blank=True),
        ),
        migrations.RunPython(populate_full_name),
    ]
